const types = {
  TOGGLE_STATUS: 'TOGGLE_STATUS',
  SORT: 'SORT',
  LIST_ALL: 'LIST_ALL',
  ADD_TASK: 'ADD_TASK',
  EDITING_TASK: 'EDITING_TASK',
  EDITED_TASK: 'EDITED_TASK',
  CLEAR_TASK_EDITING: 'CLEAR_TASK_EDITING',
  DELETE_TASK: 'DELETE_TASK',
  SHOW_FORM: 'SHOW_FORM',
  CLOSE_FORM: 'CLOSE_FORM',
  TOGGLE_FORM: 'TOGGLE_FORM'
};

export { types }